name: Sync Github Repos To Gitee

on:
  push:
    branches: 
      - master


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:lxlfpeng/MakeJson.git"
          destination-repo: "git@gitee.com:DaPengDePeng/make-json.git"
