#任务名称
name: MakeJson2Gitee
# 触发 workflow 的事件
on: [push]
# 一个workflow由执行的一项或多项job
jobs:
  # 一个job任务，任务名为build
  build:
    #使用ubuntu的运行环境 版本为最新版
    runs-on: ubuntu-latest
    #步骤
    steps:
    - name: push2giteeother
      #需要用到wearerequired/git-mirror-action 文档:https://github.com/wearerequired/git-mirror-action
      uses: wearerequired/git-mirror-action@master
      #配置环境变量
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
      #给Action传入数据
      with:
        #源仓库(这里建议https的方式,源仓库是Public的,使用https就无需额外配置SSH)
        source-repo: "https://github.com/lxlfpeng/MakeJson.git"
        #目标仓库
        destination-repo: "git@gitee.com:DaPengDePeng/make-json.git"
