name: MakeJson

# 触发 workflow 的事件
on: [push]

# 一个workflow由执行的一项或多项job
jobs:
  # 一个job任务，任务名为build
  build:
      runs-on: ubuntu-latest
      steps:
      - name: checkout actions
        uses: actions/checkout@v2 # Checking out the repo
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
            pip install requests
            pip install bs4
            pip install lxml
      - name: Update paper list
        run: |
          python InformationFlow.py
      - name: commit
        run: |
          git config --global user.email 565289282@qq.com
          git config --global user.name lxlfpeng
          git add .
          git commit -m "update" -a
          git push
          git remote add gitee https://lxlfpeng:yangpeng123@gitee.com/lxlfpeng/make-json2.git
          git push -u gitee "master"
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      
