name: Sync to Gitee
on: [ push ]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Black list
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/lxlfpeng
        dst: gitee/lxlfpeng
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        clone_style: "https"
        static_list: "MakeJson"
        force_update: true
        debug: true
        timeout: '2h' 
