
name: Sync To Gitee
on: [ push ]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:lxlfpeng/MakeJson.git"
          destination-repo: "git@gitee.com:DaPengDePeng/make-json.git"      

# name: MakeJson

# # 触发 workflow 的事件
# on: [push]

# # 一个workflow由执行的一项或多项job
# jobs:
#   # 一个job任务，任务名为build
#   build:
#       runs-on: ubuntu-latest
#       steps:
#       - name: checkout actions
#         uses: actions/checkout@v2 # Checking out the repo
#       - name: Set up Python 3.7
#         uses: actions/setup-python@v1
#         with:
#           python-version: 3.7
#       - name: Install dependencies
#         run: |
#            python -m pip install --upgrade pip
#             pip install requests
#             pip install bs4
#             pip install lxml
#       - name: Update paper list
#         run: |
#           python InformationFlow.py
#       - name: commit
#         run: |
#           git config --global user.email "565289282@qq.com"
#           git config --global user.name "lxlfpeng"
#           git add .
#           git commit -m "update" -a
#           git push
#       - name: Black list
#         uses: Yikun/hub-mirror-action@master
#         with:
#           src: github/lxlfpeng
#           dst: gitee/DaPengDePeng
#           dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
#           dst_token: ${{ secrets.GITEE_TOKEN }}
#           clone_style: "https"
#           static_list: "MakeJson"
#           force_update: true
#           debug: true
#           mappings: "MakeJson=>make-json"
#           timeout: '2h'           
      

