name: Sync To Gitee  
on:
  push:
    branches: 
      - master
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:lxlfpeng/MakeJson.git"
          destination-repo: "https://gitee.com/DaPengDePeng/make-json.git"
